# Generated by Django 5.1.4 on 2026-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional)', null=True),
        ),
    ]
