# Generated by Django 5.1.4 on 2026-04-14 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_remove_std_image_url_cartnew_ordernew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Pay on Delivery'), ('card', 'Credit/Debit Card')], default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
