# Generated by Django 5.1.4 on 2025-01-17 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cat'),
        ),
    ]
