# Generated by Django 5.1.4 on 2026-04-14 01:56

from django.db import migrations


def populate_order_item_images(apps, schema_editor):
    """Populate image field for existing OrderItems from their product's image."""
    OrderItem = apps.get_model('app', 'OrderItem')
    
    # Update all OrderItems that have a product with an image
    updated_count = 0
    for item in OrderItem.objects.filter(product__isnull=False).select_related('product'):
        if item.product.image and not item.image:
            item.image = item.product.image
            item.save(update_fields=['image'])
            updated_count += 1
    
    print(f"\nUpdated {updated_count} OrderItems with product images.")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_order_item_image'),
    ]

    operations = [
        migrations.RunPython(populate_order_item_images, migrations.RunPython.noop),
    ]
