# Generated by Django 5.1.4 on 2025-01-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_date_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone_no',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
