# Generated by Django 5.1.4 on 2025-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_phone_no_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Phone_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
