# Generated by Django 5.1.4 on 2025-01-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_phone_no_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
