# Generated by Django 5.1.4 on 2025-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
